# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-create-build-spec-console.html

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Build started!
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mv target/starter-snake-java.jar starter-snake-java.jar
artifacts:
  files:
    - starter-snake-java.jar